services:
  app:
    build:
      context: . # El contexto de construcción es la raíz del repositorio
      dockerfile: .devcontainer/Dockerfile # Ruta al Dockerfile de Laravel
    container_name: laravel_app
    ports:
      - "8000:8000"
    volumes:
      # Monta la carpeta 'laravel' de tu host en '/var/www' dentro del contenedor
      - /workspaces/${localWorkspaceFolderBasename}/laravel:/var/www
    depends_on:
      postgres:
        condition: service_started
    command: tail -f /dev/null # Mantiene el contenedor ejecutándose
    networks:
      - laravel

  postgres:
    image: postgres:15-alpine
    container_name: laravel_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: laravel_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      postgres:
        condition: service_started
    networks:
      - laravel

  react-app:
    build:
      context: ./frontend # El contexto de construcción es la carpeta 'frontend'
      dockerfile: Dockerfile # Ruta al Dockerfile de React (dentro de 'frontend')
    container_name: react_app
    ports:
      - "3000:3000"
    volumes:
      # Monta la carpeta 'frontend' de tu host en '/app' dentro del contenedor React
      - /workspaces/${localWorkspaceFolderBasename}/frontend:/app
      - /app/node_modules # Volumen anónimo para que node_modules se gestione dentro del contenedor
    environment:
      - CHOKIDAR_USEPOLLING=true # Útil para hot-reloading en React en entornos virtuales
    networks:
      - laravel

volumes:
  db_data:
    driver: local

networks:
  laravel: